### PR TITLE
Sans-serif text font

### PR DESCRIPTION
**Pull request by relikd**
new css var `--text-font` defaults to `Helvetica, sans-serif;`

### CODE REVIEW

**Comment by sbarex** [comment]
The style for the `html` tag use the `-apple-system-body` font. `Helvetica, sans-serif` for the body is a better solution?

**Comment by relikd** [comment]
That does not seem to work. For one, I think it's `font-family` and not just `font`. Second, on my system `-apple-system-body` does not seem to exist and is rendered as serif. But `-apple-system` does exist (as is used by Github). But `font: -apple-system;` will not render properly, whereas `font-family: -apple-system;` does.

**Comment by relikd** [comment]
Btw. Is the `markdown.css` even used for the preview? If I make changes in it, it will reflect the changes in the host app, but not on the preview. Seems like the preview is using a different version?

**Comment by sbarex** [comment]
If you make changes on Xcode the css file is copied to the application bundle and extension bundle.

If, on the other hand, you edit it by hand inside the compiled application, the changes will only be valid for the bundle that contains it. 

If you want to create a custom css there is the options inside the preferences window.

**Comment by hazarek** [comment]
Once the plugin is ready, I'll write a theme for myself. I can make a pull request later.

**Pull request merged**
